export const symbols = {
  cursor:       '❯',
  selected:     '●',
  unselected:   '○',
  checkmark:    '✓',
  cross:        '✗',
  star:         '★',
  starEmpty:    '☆',
  warning:      '⚠',
  ai:           '✦',
  textCursor:   '█',
  separator:    '│',
  arrowUp:      '↑',
  arrowDown:    '↓',
  arrowLeft:    '←',
  arrowRight:   '→',
  bullet:       '•',
  spinner:      ['⠋','⠙','⠹','⠸','⠼','⠴','⠦','⠧','⠇','⠏'] as const,
  spinnerInterval: 80,
} as const;
